name: CI
on:
  push:
    branches:
      - main
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      with:
        fetch-depth: 0
    - name: pre-unit-tests
      run: |
        mvn test
    - name: build
      uses: werf/actions/build@v2
    - name: post-unit-tests
      uses: werf/actions/run@v2
      with:
        image: app-test-4
        args: mvn test
